In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('data/cleaned_data.csv')
data.head()

/var/folders/fm/08v38d894qqg0x2sfcmb_2mh0000gn/T/ipykernel_11353/3509429362.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('data/cleaned_data.csv')

,code,product_name,brands,categories_en,labels_en,ingredients_text,allergens_en,additives_en,nutrition_grade_fr,energy_100g,...,cocoa_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,category_level_1,category_level_2,category_level_3,category_level_4,category_level_5,category_level_6
0,4530,Banana Chips Sweetened (Whole),not mentioned,NaN,Labels are missing,"Bananas, vegetable oil (coconut oil, corn oil ...",unknown,No additives,d,2243.0,...,0.0,no information,14.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN
1,4559,Peanuts,torn & glasser,NaN,Labels are missing,"Peanuts, wheat flour, sugar, rice flour, tapio...","en:peanuts, en:soy, en:wheat",No additives,b,1941.0,...,0.0,no information,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,16087,Organic Salted Nut Mix,grizzlies,NaN,Labels are missing,"Organic hazelnuts, organic cashews, organic wa...",unknown,No additives,d,2540.0,...,0.0,no information,12.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
3,16094,Organic Polenta,bob's red mill,NaN,Labels are missing,Organic polenta,unknown,No additives,not given,1552.0,...,0.0,no information,not given,not given,NaN,NaN,NaN,NaN,NaN,NaN
4,16100,Breadshop Honey Gone Nuts Granola,unfi,NaN,Labels are missing,"Rolled oats, grape concentrate, expeller press...",en:sesame,No additives,not given,1933.0,...,0.0,no information,not given,not given,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.set_option('display.max_colwidth', None)
data[data.product_name=='Dark Chocolate Bar'][['code', 'category_level_1','category_level_2', 'ingredients_text']]

,code,category_level_1,category_level_2,ingredients_text
14361,18894412373,NaN,NaN,"Dark chocolate (sugar, unsweetened chocolate, cocoa butter, unsweetened chocolate processed with alkali, soy lecithin [an emulsifier], salt, vanilla extract)."
54675,42704044737,NaN,NaN,"Dark chocolate (sugar, chocolate liquor, chocolate liquor processed with alkali, cocoa butter, butterfat, soy lecithin and vanilla)."
57405,46567031705,NaN,NaN,"Dark chocolate (cocoa mass, sugar, cocoa butter, soy lecithin [emulsifier], and natural vanilla extract)."
57455,46567034041,NaN,NaN,"Dark chocolate (cocoa mass, sugar, cocoa butter, soy lecithin [emulsifier], and natural vanilla extract), toffee bits (sugar, butter, soy lecithin, and salt), honey powder (honey, maltodextrin), chipotle chile pepper powder (dried chipotle chiles), and na"
63723,52745980086,NaN,NaN,"Dark chocolate (sugar, chocolate liquor {rocessed with alkali}, cocoa butter, whole milk powder, milkfat, soy lecithin {an emulsifier}, vanilla extract), milk chocolate (sugar, cocoa butter, chocolate liquor, skim milk powder, milkfat, whole milk powder, soy lecithin, vanilla extract), chocolate micro cookie gems (enriched flour {wheat flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid}, sugar, cocoa processed with alkali, vegetable oil shortening {partially hydrogenated soybean and/or cottonseed oils}, high fructose corn syrup, corn flour, chocolate liquior, salt, dextrose, sodium bicarbonate, soy lecithin), pure peppermint oil."
66528,68116101011,NaN,NaN,"Cocoa mass, cane sugar, cocoa butter, non-gmo sunflower lecithin."
109296,0182280000007,NaN,NaN,"Figs, cocoa, dark chocolate(sugar, cocoa mass processed with alkali, cocoa butter, butter oil, soy lecithin, vanilla), almonds, sugar, invert sugar, natural flavor, canola oil, salt, cream of tartar."
109298,0182280000083,NaN,NaN,"Chicory fiber, peanut fiber, dark chocolate(sugar, cocoa mass processed with alkali, cocoa butter, butter oil, soy lecithin, vanilla), peanut butter(peanuts), brown rice flour, dextrose, brown rice syrup, salt, natural flavors."
122797,688267179051,NaN,NaN,"Dark chocolate (cocoa mass, sugar, cocoa butter, soy lecithin [emulsifier], vanilla extract), filling (caramel [corn syrup, butter, sugar, hydrogenated coconut oil, fructose, milk, emulsifiers {mono and diglycerides, soy lecithin}, salt, natural and artif"
126446,711175116174,NaN,NaN,"Dark chocolate (unsweetened chocolate, sugar, cocoa butter, soy lecithin [an emulsifier], vanilla)."
126468,711175123264,NaN,NaN,"Dark chocolate (unsweetened chocolate, sugar, cocoa butter, soy lecithin [an emulsifier], vanilla), freeze dried strawberries, sugar, fresh herbs."
132481,729582116458,NaN,NaN,"Center (rice syrup, dried coconut, almonds), dark chocolate coating (evaporated cane syrup, unsweetened chocolate+, cocoa butter+, soy lecithin, natural vanilla)."
134822,741360730908,NaN,NaN,"Cacao, pure cane sugar, cocoa butter, pure tahitian vanilla, roasted coffee beans."
145007,810815020700,NaN,NaN,"Semisweet dark chocolate [evaporated cane juice, chocolate liquor (processed with alkali), cocoa butter, milk fat, soya lecithin (an emulsifier), and vanilla], organic honey, whey protein isolate, almond butter, coconut, almonds, vitamins & minerals [dica"
145968,812603017824,NaN,NaN,"Cacao beans*, cane sugar*, cacao butter*, soy lecithin."
156851,853522000726,NaN,NaN,"Natural chocolate liquor (non-alcoholic), evaporated cane juice, non-dairy cocoa butter."

In [4]:
from modules.ingredients import clean_ingredients

data['ingredients'] = data['ingredients_text'].apply(clean_ingredients)

data['ingredients_text'] = data['ingredients_text'].apply(clean_ingredients)

In [5]:
pd.set_option('display.max_colwidth', None)
data[data.product_name=='Dark Chocolate Bar'][['code', 'category_level_1','category_level_2', 'ingredients']]

,code,category_level_1,category_level_2,ingredients
14361,18894412373,NaN,NaN,dark chocolate
54675,42704044737,NaN,NaN,dark chocolate
57405,46567031705,NaN,NaN,dark chocolate
57455,46567034041,NaN,NaN,"dark chocolate , toffee bits , honey powder , chipotle chile pepper powder , and na"
63723,52745980086,NaN,NaN,"dark chocolate , milk chocolate , chocolate micro cookie gems , pure peppermint oil"
66528,68116101011,NaN,NaN,"cocoa mass, cane sugar, cocoa butter, non-gmo sunflower lecithin"
109296,0182280000007,NaN,NaN,"figs, cocoa, dark chocolate, almonds, sugar, invert sugar, natural flavor, canola oil, salt, cream of tartar"
109298,0182280000083,NaN,NaN,"chicory fiber, peanut fiber, dark chocolate, peanut butter, brown rice flour, dextrose, brown rice syrup, salt, natural flavors"
122797,688267179051,NaN,NaN,"dark chocolate , filling"
126446,711175116174,NaN,NaN,dark chocolate
126468,711175123264,NaN,NaN,"dark chocolate , freeze dried strawberries, sugar, fresh herbs"
132481,729582116458,NaN,NaN,"center , dark chocolate coating"
134822,741360730908,NaN,NaN,"cacao, pure cane sugar, cocoa butter, pure tahitian vanilla, roasted coffee beans"
145007,810815020700,NaN,NaN,"semisweet dark chocolate , organic honey, whey protein isolate, almond butter, coconut, almonds, vitamins & minerals"
145968,812603017824,NaN,NaN,"cacao beans*, cane sugar*, cacao butter*, soy lecithin"
156851,853522000726,NaN,NaN,"natural chocolate liquor , evaporated cane juice, non-dairy cocoa butter"

### Pre-processing

In [6]:
# Clean and standardize text columns
def clean_text(text):
    if isinstance(text, str):
        return text.lower().strip()
    return text

#data['product_name'] = data['product_name'].apply(clean_text)
data['ingredients'] = data['ingredients'].apply(clean_text)
data['category_level_1'] = data['category_level_1'].apply(clean_text)
data['category_level_2'] = data['category_level_2'].apply(clean_text)

In [7]:
# Replace placeholders with NaN or empty lists
data['ingredients'] = data['ingredients'].replace('ingredients are missing', np.nan)
# Split columns into lists
data['ingredients'] = data['ingredients'].str.split(', ')

### Implement product matching

In [ ]:
from fuzzywuzzy import process

def find_top_matches(user_input, choices, limit=5):
    matches = process.extract(user_input, choices, limit=limit)
    return matches

In [ ]:
# # Example: User inputs a product name
# user_input = "dark chocolate bar"
# top_matches = find_top_matches(user_input, data['product_name'].tolist())

# print(f"Top matches for '{user_input}':")
# for match, score in top_matches:
#     print(f"- {match} (Score: {score})")

### Recommendations Example Usage

In [23]:
from modules.ingredient_recommendations import recommend_products
from modules.ingredient_recommendations import recommend_by_ingredients

# Example usage
user_input = "dark chocolate bar"  # User's input product name
allergens_to_avoid = ['wheat', 'peanuts']  # Allergens to avoid

recommendations = recommend_products(user_input, data, top_n=5, allergens_to_avoid=allergens_to_avoid)

# Print recommendations
print("Final recommendations:")
print(recommendations[['product_name', 'additives_en', 'allergens_en']].to_string(index=False))

Final recommendations:
                                                  product_name                                          additives_en    allergens_en
                                  Dark Chocolate Coconut Chews                                            E322,E322i       milk, soy
                   Dark Chocolate Sea Salt & Turbinado Almonds                                            E322,E322i       milk, soy
M&S Extrenely Chocolatey Milk, Dark & White Chocolate Biscuits E160a,E170,E322,E322i,E330,E375,E450,E500,E500ii,E503 milk, eggs, soy
                    All Butter Cookies Belgian Chocolate Chunk                       E170,E375,E450,E500,E500ii,E503       milk, soy

### Recommendations Example Usage using bar_code

In [ ]:
from modules.recommendations_code import recommend_products
from modules.recommendations_code import recommend_by_ingredients

# Example usage
bar_code = "711175123264"  # User's input product name
allergens_to_avoid = ['wheat', 'peanuts']  # Allergens to avoid

recommendations = recommend_products(bar_code, data, top_n=5, allergens_to_avoid=allergens_to_avoid)

# Check if recommendations is None
if recommendations is None or recommendations.empty:
	print("No recommendations found. Please check the input data or function implementation.")
else:
	# Print recommendations
	print("Final recommendations:")
	print(recommendations[['product_name', 'additives_en', 'allergens_en']].to_string(index=False))

### Radial chart

In [ ]:
import pandas as pd
from modules.radar_chart import preprocess_data, create_nutrition_radar_charts, create_combined_radar

# Define the columns to analyze
category_col = 'category_level_1'
nutrient_cols = ['energy_100g', 'proteins_100g', 'carbohydrates_100g', 'fiber_100g', 'fat_100g']

# Preprocess the data
top_category_nutrition = preprocess_data(data, category_col, nutrient_cols, top_n=10)

# Extract categories and values
categories = top_category_nutrition[category_col]
values = top_category_nutrition[nutrient_cols]

# Create a radar chart
#create_radar_chart(categories, values, title='Top 10 Primary Categories by Nutritional Facts')
#create_nutrition_radar_charts(categories, values, title='Top 10 Primary Categories by Nutritional Facts')
create_combined_radar(categories, values)

# Do not run the code from here

## Ingredient based recommendations using tokenization, embeddings and clustering

### Pre-processing and Vectorization

In [9]:
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk 
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')  
nltk.download('omw-1.4')

ingredients = data.ingredients_text

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/krishvenigalla/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/krishvenigalla/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/krishvenigalla/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/krishvenigalla/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/krishvenigalla/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

### Step 1 : Preprocessing with Lemmatization

In [10]:
def preprocess(text):
    
    text = re.sub(r'[^\w\s]', '', text)
    
    # Tokenization
    tokens = word_tokenize(text)
    
    # Remove stop words
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    
    return ' '.join(tokens)

cleaned_ingredients = [preprocess(item) for item in ingredients]

print("Cleaned Ingredients:")
cleaned_ingredients[:5]

Cleaned Ingredients:

['banana vegetable oil sugar natural banana flavor',
 'peanut wheat flour sugar rice flour tapioca starch salt leavening soy sauce potato starch',
 'organic hazelnut organic cashew organic walnut almond organic sunflower oil sea salt',
 'organic polenta',
 'rolled oat grape concentrate expeller pressed canola oil sunflower seed almond walnut oat bran sesame seed cashew natural vitamin e']

### Step 2 : Generate Embeddings with Sentence Transformers

In [12]:
from sentence_transformers import SentenceTransformer

# Load a pre-trained Sentence Transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings for the cleaned and lemmatized data
ingredient_embeddings = model.encode(cleaned_ingredients, show_progress_bar=True)

# Print the shape of the embeddings
print(f"Embeddings shape: {ingredient_embeddings.shape}")

Batches:   0%|          | 0/9125 [00:00<?, ?it/s]

Embeddings shape: (291981, 384)

### Step 3 : Clustering with K-Means (this is a different method)

In [ ]:
# from sklearn.cluster import KMeans

# k = 10  
# kmeans = KMeans(n_clusters=k, random_state=42)
# cluster_labels = kmeans.fit_predict(ingredient_embeddings)

# # Map cluster labels back to ingredients
# clustered_ingredients = pd.DataFrame({
#     'Ingredient': ingredients,
#     'Cleaned_Ingredient': cleaned_ingredients,
#     'Cluster': cluster_labels
# })


# print("\nClustered Data:")
# print(clustered_ingredients)

### Step 3 : Similarity search with FAISS

In [21]:
import faiss
import numpy as np

# Step 1: Normalize embeddings (critical for cosine similarity)
ingredient_embeddings_normalized = ingredient_embeddings / np.linalg.norm(ingredient_embeddings, axis=1, keepdims=True)

# Step 2: Create FAISS index (cosine similarity = Inner Product on normalized vectors)
dimension = ingredient_embeddings.shape[1]
index = faiss.IndexFlatIP(dimension)  # Inner Product ≈ Cosine Similarity
index.add(ingredient_embeddings_normalized.astype('float32'))

# Step 3: Query (normalize the query too!)
query = "dark chocolate bar"
query_embedding = model.encode([query])
query_embedding_normalized = query_embedding / np.linalg.norm(query_embedding, axis=1, keepdims=True)
k = 5
distances, indices = index.search(query_embedding_normalized.astype('float32'), k)

# Step 4: Map results to ingredients
results = [(ingredients[idx], distances[0][i]) for i, idx in enumerate(indices[0])]
print(f"Top {k} matches for '{query}': {results}")

Top 5 matches for 'dark chocolate bar': [('dark chocolate', 0.846444), ('dark chocolate', 0.846444), ('dark chocolate', 0.846444), ('dark chocolate', 0.846444), ('dark chocolate', 0.846444)]

### Save the embeddings

In [22]:
import numpy as np

# Save embeddings to a file
np.save('embeddings/ingredient_embeddings.npy', ingredient_embeddings)

In [ ]:
# # Optionally, save the cleaned data and cluster labels for reference
# import pandas as pd
# clustered_ingredients = pd.DataFrame({
#     'Ingredient': ingredients,
#     'Cleaned_Ingredient': cleaned_ingredients,
#     'Cluster': cluster_labels
# })
# clustered_ingredients.to_csv('data/clustered_ingredients.csv', index=False)